name: Build APK

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Tools
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk aidl
          pip install buildozer cython==0.29.33 kivy

      - name: Build
        run: |
          buildozer init
          sed -i 's/# android.accept_sdk_license = False/android.accept_sdk_license = True/' buildozer.spec
          sed -i 's/android.archs = armeabi-v7a/android.archs = arm64-v8a/' buildozer.spec
          yes | buildozer -v android debug

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: App-Package
          path: bin/*.apk
